name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install Dependencies
      run: sudo apt install -y libwebkit2gtk-4.0-dev mingw-w64
    - name: Build Linux x64
      run: GOARCH="amd64" GOOS="linux" go build -o ./dist/octii-desktop-linux-x64 -v ./main.go 
    - name: Build MacOS x64
      run: GOARCH="amd64" GOOS="darwin" go build -o ./dist/octii-desktop-macos-x64 -v ./main.go
    - name: Build MacOS ARM
      run: GOARCH="arm64" GOOS="darwin" go build -o ./dist/octii-desktop-macos-arm64 -v ./main.go
    - name: Build Windows x64
      run: GOARCH="amd64" GOOS="windows" go build -o ./dist/octii-desktop-windows-x64.exe -v ./main.go

